### ISSUE TITLE
File names ending with a period

### ISSUE THREAD

**Issue by renr4** [arter97/exfat-linux#10]
Is it possible to add support for file names without an extension like "test." with a period at the end? Because right now it is not compatible with ecryptfs.

**Comment by arter97** [comment]
The master branch is now rebased to a different base, and all existing previous issues need to be re-evaluated.

https://github.com/arter97/exfat-linux/releases/tag/5.8-1arter97

Please re-open this if you believe the new base is still susceptible to this issue.
