### ISSUE TITLE
All issues and pull-requests on hold

### ISSUE THREAD

**Issue by arter97** [arter97/exfat-linux#17]
This driver will be rebased to Linux 5.7 upstream in the coming weeks, which is yet again very different from the current code base.

Once this gets rebased, all existing issues and pull-requests will be closed and you'll have to re-evaluate and send it again, if still applicable.

https://www.phoronix.com/scan.php?page=news_item&px=New-exFAT-For-Linux-5.7

**Comment by btaroli** [comment]
Once there is native support for the filesystem in the kernel, will these other modules even be required on an ongoing basis?

**Comment by arter97** [comment]
Not really, except for supporting older kernels.

So I intend to keep this maintained until most Android kernels are updated to 5.7+.
