### ISSUE TITLE
NFS - exportfs: does not support NFS export

### ISSUE THREAD

**Issue by tapufd** [arter97/exfat-linux#18]
Hi,
I'm using your driver on Raspbian Buster, and it works fine and fast for my exfat USB disk.
I'm trying to export the mountpoint via NFS now, but whatever I do, I get the message that the mountpoint does not support NFS export.
From what I understand this also needs to be enabled in the driver? Correct?
Is it? And if not, can it be?
If it is, can you maybe help me with the NFS export of my exfat drive?
Many thanks for looking into this...
Br, T

**Comment by arter97** [comment]
The master branch is now rebased to a different base, and all existing previous issues need to be re-evaluated.

https://github.com/arter97/exfat-linux/releases/tag/5.8-1arter97

Please re-open this if you believe the new base is still susceptible to this issue.

**Comment by heartbleeded** [comment]
@tapufd  @arter97 I'd like to re-open this. NFS is a standard feature for any filesystems. Please support NFS otherwise many people need to stick to exfat-nofuse at the moment.
