### ISSUE TITLE
Build error when CONFIG_GCC_PLUGIN_RANDSTRUCT enabled in kernel.

### ISSUE THREAD

**Issue by barthess** [arter97/exfat-linux#2]
```
/usr/src/exfat-linux/fatent.c:97:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
   97 |  exfat_ent_get,
      |  ^~~~~~~~~~~~~
/usr/src/exfat-linux/fatent.c:97:2: note: (near initialization for ‘exfat_ent_ops’)
/usr/src/exfat-linux/fatent.c:97:2: error: invalid initializer
/usr/src/exfat-linux/fatent.c:97:2: note: (near initialization for ‘exfat_ent_ops.<anonymous>’)
/usr/src/exfat-linux/fatent.c:98:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
   98 |  exfat_ent_set
      |  ^~~~~~~~~~~~~
/usr/src/exfat-linux/fatent.c:98:2: note: (near initialization for ‘exfat_ent_ops’)
cc1: some warnings being treated as errors
```
Reproduces in 5.3.0 and 5.2.14
I have no ideas how to properly fix it so no patch submitted.

**Comment by arter97** [comment]
Can you post the full defconfig used for that kernel?

I'm not familiar with gcc-plugins and somehow I'm failing to enable CONFIG_GCC_PLUGIN_RANDSTRUCT.

**Comment by barthess** [comment]
I don't know what is defconfig. I just "make xconfig". Then go to "General architecture-dependent options" -> "GCC plugins" and tick "Randomize layout of sensitive kernel structures" checkbox. See my .config file in attache.
[.config.gz](https://github.com/arter97/exfat-linux/files/3627823/default.config.gz)

**Comment by arter97** [comment]
There were some code refactoring done and ent_ops were one of them.

My development workflow still can't enable GCC plugins for some reason.
If you find the next release still having the issue, please open another issue.

Thanks.
