### ISSUE TITLE
Add (fake) symlink support

### ISSUE THREAD

**Issue by mkst** [arter97/exfat-linux#22]
[exfat-nofuse](https://github.com/dorimanx/exfat-nofuse) supports [symlinks](https://github.com/dorimanx/exfat-nofuse/blob/051167ceccbe75d9d77fc4f5356f5a39a01779e8/exfat_api.h#L70).

It doesn't look *too* difficult to port over the code from nofuse that handles symlinks.

Non-exhaustive list of changes:

- [ ] Add definitions for `TYPE_SYMLINK` and `ATTR_SYMLINK` to `exfat_fs.h` and `exfat_raw.h`
- [ ] Add `target` to `exfat_inode_info` struct (?)
- [ ] Update `exfat_set_entry_type` to set attributes when encountering a symlink
- [ ] Update `exfat_make_mode` in `exfat_super.h`
- [ ] Add `exfat_symlink_inode_operations` in `file.c` along with definitions of `exfat_follow_link` / `exfat_get_link`
- [ ] Update `exfat_fill_inode` in `inode.c` to call exfat_symlink_inode_operations when dealing with a symlink
- [ ] Add `exfat_symlink` to `namei.c` to handle symlink creation
- [ ] Update `inode_operations` to add `.symlink`
- [ ] Update `exfat_lookup` to handle symlinks
- [ ] Anything that is missing from this list...

I'm hacking my way through the list, if I get to the point where I can get symlinks to work I'll raise a PR. If anyone wants to tackle this in the meantime, that would be swell :)

**Comment by arter97** [comment]
Previous branch from this also supports symlink.

It's left out this time to stay more inline with upstream's code and exFAT standard itself.

If you absolutely need symlink support, try out the old branch.

**Comment by mkst** [comment]
old branch gives me the same response as 5.4 kernel:

```
ln: failed to create symbolic link 'bar': Unknown error 524
```

Is there a specific revision of the `old` branch I should be trying?

**Comment by arter97** [comment]
Did you use the symlink mount option?

**Comment by mkst** [comment]
Aha. `symlink=1` sorted it. Thankyou!

**Comment by piranna** [comment]
What's the reason to don't have the symlinks feature behing a flag, both here or upstream? In fact, symlink hack could be used in all FAT filesystems in upstream kernel...

**Comment by arter97** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/staging.git/commit/drivers/staging/exfat?h=main&id=bb9397a356c6cc9a6e1d45633476fe83cf15a95f
