### ISSUE TITLE
Build fails with linux 5.8.1

### ISSUE THREAD

**Issue by nezumisama** [arter97/exfat-linux#27]
Building via DKMS fails with linux 5.8.1 with the following messages:
```
CC [M]  /var/lib/dkms/exfat-5.8/1/build/inode.o
/var/lib/dkms/exfat-5.8/1/build/inode.c: In function ‘exfat_readpages’:
/var/lib/dkms/exfat-5.8/1/build/inode.c:367:9: error: implicit declaration of function ‘mpage_readpages’; did you mean ‘mpage_readpage’? [-Werror=implicit-function-declaration]
  367 |  return mpage_readpages(mapping, pages, nr_pages, exfat_get_block);
      |         ^~~~~~~~~~~~~~~
      |         mpage_readpage
cc1: some warnings being treated as errors
```

**Comment by arter97** [comment]
I don't intend to support kernels above v5.7 as the included exfat driver is more or less the same as this one.

**Comment by makefu** [comment]
hey @arter97 thanks for the info, however it seems i am only able to open ps4-formatted exfat with your driver. It neither works with exfat-fuse nor with the (now built-in) exfat kernel code.
