### ISSUE TITLE
How to change mount default option to symlink=1?

### ISSUE THREAD

**Issue by eMPee584** [arter97/exfat-linux#3]
We're trying to put a (parts?) of a root fs on here.. (live linux, overlay)..
Also, how to set the system/hidden attribute on files so windows won't see?

**Comment by arter97** [comment]
> We're trying to put a (parts?) of a root fs on here.. (live linux, overlay)..

Not sure how mounting procedure is done under your circumstance, but having a look at fstab would be the first step.

> Also, how to set the system/hidden attribute on files so windows won't see?

More than likely this driver won't support such non-standard stuffs.

**Comment by eMPee584** [comment]
> Not sure how mounting procedure is done under your circumstance, but having a look at fstab would be the first step.

Well obviously our mounting takes place without fstab, that's why I asked how to change the default.

> > Also, how to set the system/hidden attribute on files so windows won't see?
> More than likely this driver won't support such non-standard stuffs.

FAT filesystem attributes are not "non-standard stuff" .. `man fatattr(1)`

**Comment by piranna** [comment]
> Well obviously our mounting takes place without fstab, that's why I asked how to change the default.

You can pass flags when doing the initial mount. Also, maybe a remount with the new flags would work.


> > Also, how to set the system/hidden attribute on files so windows won't see?
> 
> More than likely this driver won't support such non-standard stuffs.

Maybe these attributes could be bi-directionally mapped using extended attributes...
