### ISSUE TITLE
Official source for the Samsung exfat driver

### ISSUE THREAD

**Issue by josephernest** [arter97/exfat-linux#32]
Where is the official source for the Samsung exfat driver? Would you have the link of the webpage / contact of maintainer?

Is it this one: https://github.com/bkuhn/exfat ? (There is nothing since 2013 there).
https://gitorious.org/binbang/exfat-linux is not working anymore.

Here is another one: https://github.com/dorimanx/exfat-nofuse

Where is the "main" repository? It would be interesting to centralize the development there.

**Comment by arter97** [comment]
It used to be https://opensource.samsung.com/main for the older branch.

Now it's https://git.kernel.org/pub/scm/linux/kernel/git/linkinjeon/exfat.git/
