### ISSUE TITLE
Issue with Kernel 5.8.0-38-generic 

### ISSUE THREAD

**Issue by itsrexb** [arter97/exfat-linux#36]
$ sudo apt install exfat-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  exfat-dkms
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
Need to get 69.7 kB of archives.
After this operation, 387 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/arter97/exfat-linux/ubuntu focal/main amd64 exfat-dkms all 2.2.0-3arter97-0~201910290835~ubuntu20.04.1 [69.7 kB]
Fetched 69.7 kB in 2s (30.6 kB/s)     
Selecting previously unselected package exfat-dkms.
(Reading database ... 214465 files and directories currently installed.)
Preparing to unpack .../exfat-dkms_2.2.0-3arter97-0~201910290835~ubuntu20.04.1_all.deb ...
Unpacking exfat-dkms (2.2.0-3arter97-0~201910290835~ubuntu20.04.1) ...
Setting up exfat-dkms (2.2.0-3arter97-0~201910290835~ubuntu20.04.1) ...
Loading new exfat-2.2.0-3arter97-0~201910290835~ubuntu20.04.1 DKMS files...
Building for 5.8.0-38-generic
Building initial module for 5.8.0-38-generic
Error! Bad return status for module build on kernel: 5.8.0-38-generic (x86_64)
Consult /var/lib/dkms/exfat/2.2.0-3arter97-0~201910290835~ubuntu20.04.1/build/make.log for more information.
dpkg: error processing package exfat-dkms (--configure):
 installed exfat-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 exfat-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by arter97** [comment]
Please see #34 and #35
