### ISSUE TITLE
 modprobe exfat return an error.

### ISSUE THREAD

**Issue by lxjin81** [arter97/exfat-linux#4]
git clone,  make, make install,every thing is ok. 
This is the modinfo exfat infos:
modinfo exfat
filename:       /lib/modules/3.10.40-lasyka+/ext_modules/exfat.ko
author:         Samsung Electronics Co., Ltd.
description:    FAT/exFAT filesystem support
license:        GPL
alias:          fs-exfat
depends:        
vermagic:       3.10.40-lasyka+ SMP preempt mod_unload ARMv7 

but when  modprobe exfat return an error:
modprobe exfat
modprobe: ERROR: could not insert 'exfat': Unknown symbol in module, or unknown parameter.
and the dmesg show this error:
 exfat: Unknown symbol _GLOBAL_OFFSET_TABLE_ (err 0)

**Comment by arter97** [comment]
Looks like you're building a separate kernel module for Android.

Kernel modules are required to be built without position-independent code generation(PIC).
If you're using an Android toolchain, the kernel's Makefile should have `KBUILD_CFLAGS += -fno-pic`.
Or, a better solution would be using a toolchain that doesn't target Android(hence not using PIC by default).

As a temporary solution, please try adding `ccflags-y := -fno-pic` under `exfat-objs` on Makefile.

Closing as this isn't an issue directed from this project.
