### ISSUE TITLE
Add quiet mount option

### ISSUE THREAD

**Issue by yenon** [arter97/exfat-linux#5]
Some programs, especially old ones, simply don't want to work without chmod'ing files in their directories. The quiet option on fat usually allows any chmod request, but makes it fail silently.
Other than this single problem, superb work!

**Comment by arter97** [comment]
New version `2.2.0-3arter97` is up for adding quiet option.
Also published to Ubuntu PPA.

Let me know if you encounter any issues.

**Comment by yenon** [comment]
Thanks for the quick update. Everything seems to be working just fine and the application is working now.
PS: I hope this doesn't reopen the issue
