### ISSUE TITLE
exfat mount option codepage not work

### ISSUE THREAD

**Issue by ptpt52** [arter97/exfat-linux#8]
```
mount -t exfat -o codepage=cp437 /dev/sda1 /mnt/sda1
mount: mounting /dev/sda1 on /mnt/sda1/ failed: Invalid argument
```
and
```
mount -t exfat /dev/sda1 /mnt/sda1
work and codepage is default to cp936 on my ubuntu
```

**Comment by arter97** [comment]
Please post kernel log(dmesg) after the failing command.

**Comment by ptpt52** [comment]
log:
```
[ 6472.167084] exFAT-fs (sda1[8:1]): trying to mount...
[ 6472.172248] exFAT-fs (sda1[8:1]): failed to parse options
[ 6472.177764] exFAT-fs (sda1[8:1]): failed to mount! (-22)
```

**Comment by ptpt52** [comment]
also these option on works
```
delayed_meta
bps=512
```

**Comment by ptpt52** [comment]
I notice it
```
codepage=936
```
works

but
```
ls -l sda1/
ls: sda1/xxx.txt: No such file or directory
ls: sda1/1234.img: No such file or directory
```
cannot read files in /mnt/sda1/

**Comment by ptpt52** [comment]
more info:
I `touch /mnt/sda1/xxx.txt` on my Ubuntu x86_64 with exfat-linux
and try  to read on Openwrt mips_24k, failed to read files

and 
if I `touch /mnt/sda1/abc.txt` on Openwrt mips_24k
and try to read on Ubuntu, failed....

**Comment by ptpt52** [comment]
@arter97  hi
any progress?

**Comment by ptpt52** [comment]
Please help fix this bug?

**Comment by arter97** [comment]
I'm sorry, I've been busy with my Uni past few weeks.

Can you explain why you're customizing charset?
Does default not work as expected?

**Comment by ptpt52** [comment]
for now it is not about charset
My usb disk format in linux with exfat-nofuse
and create some files into it

then put it to system with exfat-linux, it could not read files
logs:
```
ls -l sda1/
ls: sda1/xxx.txt: No such file or directory
ls: sda1/1234.img: No such file or directory
```

**Comment by arter97** [comment]
Is codepage 437 and charset utf8 available in your kernel?
Please check your kernel config and look for these:
CONFIG_NLS_CODEPAGE_437=y
CONFIG_NLS_UTF8=y

**Comment by ptpt52** [comment]
yes,  codepage 437 and charset utf8 is ready in my kernel.

**Comment by arter97** [comment]
So to sum up, your x86's Ubuntu setup works nicely but your MIPS based OpenWrt have encoding issues?

**Comment by ptpt52** [comment]
x86 Ubuntu with exfat-linux not work too

Park Ju Hyung <notifications@github.com> 于 2019年12月23日周一 17:41写道：

**Comment by arter97** [comment]
> more info:
> I `touch /mnt/sda1/xxx.txt` on my Ubuntu x86_64 with exfat-linux
> and try to read on Openwrt mips_24k, failed to read files
> 
> and
> if I `touch /mnt/sda1/abc.txt` on Openwrt mips_24k with exfat-linux
> and try to read on Ubuntu, failed....

Is this still the main issue?
I'm failing to understand what really is the issue now.

**Comment by ptpt52** [comment]
yes

**Comment by arter97** [comment]
Did you change CONFIG_EXFAT_DEFAULT_CODEPAGE or CONFIG_EXFAT_DEFAULT_IOCHARSET on your MIPS kernel?

**Comment by ptpt52** [comment]
no, I never change the CONFIG_EXFAT_DEFAULT_CODEPAGE....

it maybe some bug related to mips vs x86

**Comment by arter97** [comment]
Were there any build warnings when you were building exFAT on MIPS?
What kernel version is your router running?

**Comment by ptpt52** [comment]
I do test again
I format my usb disk on windows 10 to exfat
and copy some files into it.

then put the usb disk to my Openwrt mips router with exfat-linux
read failed:
```
root@X-WRT:~# ls /mnt/sda1/
ls: /mnt/sda1/System Volume Information: No such file or directory
ls: /mnt/sda1/node.exe: No such file or directory
ls: /mnt/sda1/node_etw_provider.man: No such file or directory
ls: /mnt/sda1/nodevars.bat: No such file or directory
ls: /mnt/sda1/npm: No such file or directory
ls: /mnt/sda1/npm.cmd: No such file or directory
ls: /mnt/sda1/npx: No such file or directory
ls: /mnt/sda1/npx.cmd: No such file or directory
```

kernel 4.19.86

build with no warnning.

**Comment by ptpt52** [comment]
and more info to you:
on mipsel system, exfat-linux work fine
```
root@X-WRT:~# ls -l /mnt/sda1/
drwxrwxrwx    2 lede     lede        131072 Dec 23 19:37 System Volume Information
-rwxrwxrwx    1 lede     lede      28787352 Dec 17 06:55 node.exe
-rwxrwxrwx    1 lede     lede          8969 Oct 10 06:01 node_etw_provider.man
-rwxrwxrwx    1 lede     lede           702 Oct 10 06:01 nodevars.bat
-rwxrwxrwx    1 lede     lede           930 Dec 13 06:01 npm
-rwxrwxrwx    1 lede     lede           483 Oct 10 06:01 npm.cmd
-rwxrwxrwx    1 lede     lede           922 Dec 13 06:01 npx
-rwxrwxrwx    1 lede     lede           539 Oct 10 06:01 npx.cmd
```

**Comment by arter97** [comment]
So this could be a big endian issue, I believe this particular driver wasn't tested on a big endian system.
I'll have a look after the holidays.

**Comment by ptpt52** [comment]
Thank you for your time and wish you a happy holiday

**Comment by ptpt52** [comment]
I am trying to fix it, Please review

**Comment by arter97** [comment]
Endian sanity check needs to be done more thoroughly, I'll review the entire code after the holidays.
Meanwhile, it'll be great if you can confirm whether your attempt fixes your issue.

Thanks.

**Comment by arter97** [comment]
The master branch is now rebased to a different base, and all existing previous issues need to be re-evaluated.

https://github.com/arter97/exfat-linux/releases/tag/5.8-1arter97

Please re-open this if you believe the new base is still susceptible to this issue.
